- README.md
Přidal jsem do readme popis setupu testů
> test: add info about setup to readme

- src/Config.php
> default values for optional config params

- src/App.php
- src/ConfigDefinition.php
- tests/AppTest.php
- tests/config.json
> allow disable of table export

- src/App.php
- tests/AppTest.php
Tak ty csvčka se v multiloadu vůbec nepřidávaly do toho zip balíčku. 😞 https://github.com/keboola/gooddata-writer-v3/compare/jakub-multi-fix?expand=1#diff-58980ac23a3a9a0b92abd9805eed1e78R103
> Fix adding csv files to multiload

- src/Component.php
To by mohlo ten Failed login v EU fixnout. ;o)
> fix: init gd backend url

- composer.json
- composer.lock
viz. https://github.com/keboola/gooddata-php-client/pull/8
> chore: update GD php client and other dependencies

- composer.lock
- tests/CsvHandlerTest.php
Update `keboola/gooddata-php-client` kvůli #35 (plus ostatní minor updaty) a fix zapomenutýho importu namespacu v testech
> fix: update dependencies (fixes #35)

- README.md
- composer.json
- composer.lock
- docker-compose.yml
- src/App.php
- src/Component.php
- src/Config.php
- src/ConfigDefinition.php
- src/ConfigurationStorage.php
- src/ModelReader.php
- tests/ApiHelper.php
- tests/AppTest.php
- tests/ConfigurationStorageTest.php
- tests/ModelReaderTest.php
Nó, snažil jsem se v `Component.php` nechat co nejmíň kódu, aby se to jakž takž otestovalo, ale stejně asi ověříme jestli to celý vůbec funguje až po releasu. ;o)
> Read model from project

- src/App.php
- src/Component.php
- tests/functional/DatadirTest.php
- tests/functional/read-model/expected/data/out/tables/categories.csv
- tests/functional/read-model/expected/data/out/tables/categories.csv.manifest
- tests/functional/read-model/expected/data/out/tables/products.csv
- tests/functional/read-model/expected/data/out/tables/products.csv.manifest
- tests/functional/read-model/expected/data/out/tables/productsgrain.csv
- tests/functional/read-model/expected/data/out/tables/productsgrain.csv.manifest
- tests/phpunit/AppTest.php
- uložení konfigurace do `parameters`
- vytvoření datových tabulek přes Storage klienta
> fix: save read model configuration

- README.md
- src/App.php
- tests/functional/DatadirTest.php
- tests/phpunit/AppTest.php
> fix: add input mappaing to read model

- README.md
update docs
- writer pozna action pod menom `readModel`(read-model nepozna) tak som upravil nazov action v docs
- configurationId parameter sync akce readModel
> update readModel docs

- src/ConfigDefinition.php
jsme zapomněli ;o) (viz. https://keboola.slack.com/archives/C02CGRFK2/p1561535455012600)
> fix: allow anchorIdentifier in ConfigDefinition

- src/App.php
- src/ConfigurationStorage.php
- tests/phpunit/ConfigurationStorageTest.php
viz. https://github.com/keboola/kbc-ui/pull/3481#issuecomment-505838140
- fix ukládání prázdných dimenzí i datasetů
- uložení description změny konfigurace
> fix empty datasets or dimensions on reading model

- README.md
- phpunit.xml.dist
- src/Component.php
- src/Config.php
- src/ConfigDefinition.php
- tests/functional/DatadirTest.php
Zatím teda zůstává i sync akce
> Allow running read model in async job

- src/Component.php
Tak ještě drobnost ;o) (aby se neprováděl check input mappingu)
> fix allow running read model in async job

- src/App.php
- tests/functional/DatadirTest.php
> Add logging

- Dockerfile
Fixes: https://keboola.atlassian.net/browse/COM-51
> fixup Rapid SSL CA

- src/run.php
https://keboola.slack.com/archives/C09U3R1J4/p1607028926013900
> add errMessage to log

- README.md
- composer.json
- composer.lock
- src/App.php
- src/Config.php
- src/StorageApiClientFactory.php
- tests/phpunit/StorageApiClientFactoryTest.php
Jira - https://keboola.atlassian.net/browse/COM-1615
> Support dev branches

- src/Config.php
- tests/functional/DatadirTest.php
Jira - https://keboola.atlassian.net/browse/CM-292
> Fix gooddata backendUrl with slash

- .github/workflows/push.yml
- Dockerfile
- composer.json
- composer.lock
- docker-compose.yml
- src/Model.php
- src/Upload.php
Jira - https://keboola.atlassian.net/browse/CM-79
před mergem je potřeba:
> Fix retry mechanism

- src/App.php
- src/Upload.php
- tests/functional/DatadirTest.php
Looks green, but actions are behaving a bit odd.
> ES-46 add a couple more log statements

- src/ModelReader.php
JIRA: https://keboola.atlassian.net/browse/CM-500
> Check if array key exist

- composer.json
- composer.lock
- src/Model.php
JIRA: https://keboola.atlassian.net/browse/CM-708
před mergem je potřeba:
> Fix issue with multiple relations

- src/Model.php
- tests/phpunit/ModelTest.php
JIRA: https://keboola.atlassian.net/browse/CM-714
@kacurez OJ je na dovolené a ty tu máš z lidí, co tu ještě pracují nejvíc commitů :D
> Fix obtaining FK name
